<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'Abort any changes and reset settings' => 'Cancelar as alterações e redefinir as configurações',
    'Apply' => 'Aplicar',
    'Are you sure you want to delete the setting?' => 'Tem certeza de que deseja excluir a configuração?',
    'Configure Order and Display of Grid Columns' => 'Configurar Ordem e Exibição das Colunas da Grid',
    'Default Filter' => 'Filtro Padrão',
    'Default Sort' => 'Ordem Padrão',
    'Delete' => 'Apagar',
    'Filter Configuration' => 'Configuração do Filtro',
    'Filter Name' => 'Nome do Filtro',
    'Grid Theme' => 'Tema da Grid',
    'Hidden / Fixed Columns' => 'Ocultos / Colunas Fixas',
    'Integer between {min} to {max}' => 'Inteiro entre {min} e {max}',
    'Page Size' => 'Tamanho da Página',
    'Personalize Grid Configuration' => 'Personalizar Configurações da Grid',
    'Personalize grid settings' => 'Personalizar configurações da grid',
    'Remove saved grid settings' => 'Remover configurações salvas da grid',
    'Reset' => 'Resetar',
    'Save' => 'Salvar',
    'Save / Edit Grid {title}' => 'Salvar / Editar Grid {title}',
    'Save / edit grid {category}' => 'Salvar / editar grid {category}',
    'Save grid settings' => 'Salvar configurações da grid',
    'Saved Filters' => 'Salvar Filtros',
    'Saved Sorts' => 'Salvar Ordenações',
    'Saving and applying configuration' => 'Salvando e aplicando as configurações',
    'Select a filter...' => 'Selecione um filtro...',
    'Select a sort...' => 'Selecione uma ordem...',
    'Select a theme...' => 'Selecione um tema...',
    'Select theme to style grid' => 'Selecione o tema da grid',
    'Select...' => 'Selecione...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Defina um nome para salvar o estado de sua {category} na grid atual. Você pode, alternativamente, selecionar uma {category} salva a partir da lista abaixo para editar ou excluir.',
    'Set default grid filter criteria' => 'Definir filtros padrões para a grid',
    'Set default grid sort criteria' => 'Definir ordenações padrões para a grid',
    'Sort Configuration' => 'Configurações de Ordenação',
    'Sort Name' => 'Nome da Ordenação',
    'Trash' => 'Lixo',
    'Trashing all personalizations' => 'Apagando configurações personalizadas',
    'Visible Columns' => 'Colunas Visíveis',
    'ascending' => 'crescente',
    'descending' => 'decrescente',
    'filter' => 'filtro',
    'grid' => 'grid',
    'rows per page' => 'Linhas por página',
    'sort' => 'ordenar',
];
