<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'filter' => '',
    'grid' => '',
    'sort' => '',
    'Abort any changes and reset settings' => 'Tühista muudatused ning lae algseaded',
    'Apply' => 'Rakenda',
    'Are you sure you want to delete the setting?' => 'Oled kindel, et tahad selle seade kustutada?',
    'Configure Order and Display of Grid Columns' => 'Seadista tabeli veergude järjestust ja nähtavust',
    'Default Filter' => 'Vaikimisi filter',
    'Default Sort' => 'Vaikimisi sorteerimine',
    'Delete' => 'Kustuta',
    'Filter Configuration' => 'Filtri seaded',
    'Filter Name' => 'Filtri nimi',
    'Grid Theme' => 'Tabeli teema',
    'Hidden / Fixed Columns' => 'Peidetud / fikseeritud veerud',
    'Integer between {min} to {max}' => 'Täisarv vahemikus {min} kuni {max}',
    'Page Size' => 'Lehe suurus',
    'Personalize Grid Configuration' => 'Tabeli konfiguratsiooni isikupärastamine',
    'Personalize grid settings' => 'Tabeli seadistuse isikupärastamine',
    'Remove saved grid settings' => 'Eemalda salvestatud tabeli seaded',
    'Reset' => 'Lähtesta',
    'Save' => 'Salvesta',
    'Save / Edit Grid {title}' => 'Salvesta / Muuda tabelit {title}',
    'Save / edit grid {category}' => 'Salvesta / muuda tabelit {category}',
    'Save grid settings' => 'Salvesta tabeli seaded',
    'Saved Filters' => 'Salvesta filtrid',
    'Saved Sorts' => 'Salvestatud järjestused',
    'Saving and applying configuration' => 'Salvestan ja rakendan seadeid',
    'Select a filter...' => 'Vali filter...',
    'Select a sort...' => 'Vali järjestus...',
    'Select a theme...' => 'Vali teema...',
    'Select theme to style grid' => 'Vali tabeli kujundamiseks teema',
    'Select...' => 'Vali...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Vali nimi, et salvestada oma tabeli {category} hetkeseis. Alternatiivina võid valida salvestud {category}, et seda muuta või kustutada.',
    'Set default grid filter criteria' => 'Vali vaikimisi tabeli filtreerimise kriteeriumid',
    'Set default grid sort criteria' => 'Vali vaikimisi tabeli sorteerimise kriteeriumid',
    'Sort Configuration' => 'Sorteerimise seaded',
    'Sort Name' => 'Sorteerimise nimi',
    'Trash' => 'Prügikast',
    'Trashing all personalizations' => 'Saadan kõik isikupärastamised prügikasti',
    'Visible Columns' => 'Nähtavad veerud',
    'ascending' => 'kasvavalt',
    'descending' => 'kahanevalt',
    'rows per page' => 'ridu lehel',
];
