<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'Abort any changes and reset settings' => 'Ακύρωση των αλλαγών και επαναφορά ρυθμίσεων',
    'Apply' => 'Εφαρμογή',
    'Are you sure you want to delete the setting?' => 'Ειστε βέβαιοι ότι θέλετε να διαγράψετε την ρύθμιση;',
    'Configure Order and Display of Grid Columns' => 'Ρύθμιση της σειράς και εμφάνισης των στηλών',
    'Default Filter' => 'Προεπιλεγμένο Φίλτρο',
    'Default Sort' => 'Προεπιλεγμένη Ταξινόμηση',
    'Delete' => 'Διαγραφή',
    'Filter Configuration' => 'Ρύθμιση Φίλτρου',
    'Filter Name' => 'Ονομα φίλτρου',
    'Grid Theme' => 'Θέμα Φίλτρου',
    'Hidden / Fixed Columns' => 'Κρυφές / Σταθερές στήλες',
    'Integer between {min} to {max}' => 'Ακαίρεος από {min} εως {max}',
    'Page Size' => 'Μέγεθος σελίδας',
    'Personalize Grid Configuration' => 'Εξατομικέυση Αρχικών Ρυθμίσεων Πίνακα',
    'Personalize grid settings' => 'Εξατομίκευση Ρυθμίσεων Πίνακα',
    'Remove saved grid settings' => 'Διαγραφή Ρυθμίσεων πίνακα',
    'Reset' => 'Επαναφορά',
    'Save' => 'Αποθήκευση',
    'Save / Edit Grid {title}' => 'Αποθήκευση / Μεταβολή Πίνακα {title}',
    'Save / edit grid {category}' => 'Αποθήκευση / Μεταβολή Πίνακα {category}',
    'Save grid settings' => 'Αποθήκευση ρυθμίσεων πίνακα',
    'Saved Filters' => 'Αποθηκευμένα φίλτρα',
    'Saved Sorts' => 'Αποθηκευμένες Ταξινομήσεις',
    'Saving and applying configuration' => 'Εφαρμογή και αποθήκευση ρυθμίσεων',
    'Select a filter...' => 'Επιλέξτε Φίλτρο...',
    'Select a sort...' => 'Επιλέξτε ταξινόμιση...',
    'Select a theme...' => 'Επιλέξτε θέμα...',
    'Select theme to style grid' => 'Επιλέξτε θέμα για το στύλ του πίνακα',
    'Select...' => 'Επιλέξτε...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Δώστε όνομα για να σώσετε την παρούσα κατσταση του πίνακα {category}.Εναλλακτικά επιλέξτε {category} απο την κάτωθι λίστα',
    'Set default grid filter criteria' => 'Ορισμος Προεπιλεγμένης ρύθμισης πίνακα',
    'Set default grid sort criteria' => 'Ορισμός Προεπιλεγμένης ταξινόμησης πίνακα',
    'Sort Configuration' => 'Ρύθμιση Ταξινόμισης',
    'Sort Name' => 'Ονομα Ταξινόμισης',
    'Trash' => 'Διαγραφή',
    'Trashing all personalizations' => 'Διαγραφή όλων των ρυθμίσεων χρήστη',
    'Visible Columns' => 'Ορατές Στήλες',
    'ascending' => 'Αυξουσα',
    'descending' => 'Ελάσουσα',
    'filter' => 'Φίλτρο',
    'grid' => 'Πίνακας',
    'rows per page' => 'Γραμμές ανα σελίδα',
    'sort' => 'Ταξινόμηση',
];
