<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apply' => 'Применить',
    'Reset' => 'Сбросить',
    'Personalize' => 'Настроить',
    'Personalize Grid Configuration' => 'Настройка таблицы',
    'Saving and applying configuration' => 'Сохранить и применить',
    'Grid Page Size' => 'Количество элементов на странице',
    'Enter any integer between {min} to {max}.' => 'Введите целые числа между {min} и {max}',
    'Grid Theme' => 'Тема оформления таблицы',
    'Select a theme to style your grid.' => 'Выберите тему для Вашей таблицы',
    'Visible Columns' => 'Отображаемые колонки',
    'Hidden / Fixed Columns' => 'Скрытые / Фиксированные колонки',
    'Configure Order and Display of Grid Columns' => 'Настроить порядок и отображение колонок',
    'rows per page' => 'строк на странице',
];
