<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort any changes and reset settings' => '',
    'Are you sure you want to delete the setting?' => '',
    'Default Filter' => '',
    'Default Sort' => '',
    'Delete' => '',
    'Filter Configuration' => '',
    'Filter Name' => '',
    'Integer between {min} to {max}' => '',
    'Page Size' => '',
    'Personalize grid settings' => '',
    'Remove saved grid settings' => '',
    'Save' => '',
    'Save / Edit Grid {title}' => '',
    'Save / edit grid {category}' => '',
    'Save grid settings' => '',
    'Saved Filters' => '',
    'Saved Sorts' => '',
    'Select theme to style grid' => '',
    'Select...' => '',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => '',
    'Set default grid filter criteria' => '',
    'Set default grid sort criteria' => '',
    'Sort Configuration' => '',
    'Sort Name' => '',
    'Trash' => '',
    'Trashing all personalizations' => '',
    'ascending' => '',
    'descending' => '',
    'Enter any integer between {min} to {max}.' => '@@Введите целые числа между {min} и {max}@@',
    'Grid Page Size' => '@@Количество элементов на странице@@',
    'Personalize' => '@@Настроить@@',
    'Select ...' => '@@@@',
    'Select a filter ...' => '@@@@',
    'Select a sort ...' => '@@@@',
    'Select a theme ...' => '@@@@',
    'Select a theme to style your grid.' => '@@Выберите тему для Вашей таблицы@@',
    'Apply' => 'Применить',
    'Configure Order and Display of Grid Columns' => 'Настроить порядок и отображение колонок',
    'Grid Theme' => 'Тема оформления таблицы',
    'Hidden / Fixed Columns' => 'Скрытые / Фиксированные колонки',
    'Personalize Grid Configuration' => 'Настройка таблицы',
    'Reset' => 'Сбросить',
    'Saving and applying configuration' => 'Сохранить и применить',
    'Select a filter...' => '@@@@',
    'Select a sort...' => '@@@@',
    'Select a theme...' => '@@@@',
    'Visible Columns' => 'Отображаемые колонки',
    'rows per page' => 'строк на странице',
];
