<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'filter' => '',
    'grid' => '',
    'sort' => '',
    'Abort any changes and reset settings' => 'Отменить все изменения и сбросить настройки',
    'Apply' => 'Применить',
    'Are you sure you want to delete the setting?' => 'Вы уверены в том, что хотите удалить настройку?',
    'Configure Order and Display of Grid Columns' => 'Настроить порядок и отображение колонок',
    'Default Filter' => 'Фильтр по-умолчанию',
    'Default Sort' => 'Сортировка по-умолчанию',
    'Delete' => 'Удалить',
    'Filter Configuration' => 'Конфигурация фильтра',
    'Filter Name' => 'Название фильтра',
    'Grid Theme' => 'Тема оформления таблицы',
    'Hidden / Fixed Columns' => 'Скрытые / Фиксированные колонки',
    'Integer between {min} to {max}' => 'Число от {min} и до {max}',
    'Page Size' => 'Записей на странице',
    'Personalize Grid Configuration' => 'Настройка таблицы',
    'Personalize grid settings' => 'Персонализировать настройки таблицы',
    'Remove saved grid settings' => 'Удалить сохраненные настройки таблицы',
    'Reset' => 'Сбросить',
    'Save' => 'Сохранить',
    'Save / Edit Grid {title}' => 'Сохранить / изменить таблицу {title}',
    'Save / edit grid {category}' => 'Сохранить / изменить таблицу {category}',
    'Save grid settings' => 'Сохранить настройки таблицы',
    'Saved Filters' => 'Сохраненные фильтры',
    'Saved Sorts' => 'Сохраненные сортировки',
    'Saving and applying configuration' => 'Сохранить и применить',
    'Select a filter...' => 'Выберите фильтр...',
    'Select a sort...' => 'Выберите сортировку...',
    'Select a theme...' => 'Выберите тему...',
    'Select theme to style grid' => 'Выберите тему для оформления таблицы',
    'Select...' => 'Выберите...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Укажите имя для сохранения текущего состояния таблицы {category}. В дополнение, вы можете выбрать сохраненную {category} из нижеследующего списка для изменения или удаления.',
    'Set default grid filter criteria' => 'Установить критерий фильтра по-умолчанию',
    'Set default grid sort criteria' => 'Установить критерий сортировки по-умолчанию',
    'Sort Configuration' => 'Конфигурация сортировки',
    'Sort Name' => 'Название сортировки',
    'Trash' => 'Удалить',
    'Trashing all personalizations' => 'Удалить все настройки',
    'Visible Columns' => 'Отображаемые колонки',
    'ascending' => 'по-возрастанию',
    'descending' => 'по-убыванию',
    'rows per page' => 'строк на странице',
];
