<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort any changes and reset settings' => 'Aborta cualquier cambio y reinicia la configuración',
    'Apply' => 'Aplicar',
    'Are you sure you want to delete the setting?' => 'Estás seguro de querer eliminar la configuración',
    'Configure Order and Display of Grid Columns' => 'Configura el orden y visibilidad de las columnas',
    'Default Filter' => 'Filtro predeterminado',
    'Default Sort' => 'Orden predeterminado',
    'Delete' => 'Eliminar',
    'Filter Configuration' => 'Configuración del filtro',
    'Filter Name' => 'Nombre del filtro',
    'Grid Theme' => 'Tema visual del Grid',
    'Hidden / Fixed Columns' => 'Ocultar / Mostrar columnas',
    'Integer between {min} to {max}' => 'Entero entren {min} y {max}',
    'Page Size' => 'Tamaño de la página',
    'Personalize Grid Configuration' => 'Personaliza la configuración del Grid',
    'Personalize grid settings' => 'Personaliza las opciones del grid',
    'Remove saved grid settings' => 'Elimina las opciones guardadas del Grid',
    'Reset' => 'Reiniciar',
    'Save' => 'Guardar',
    'Save / Edit Grid {title}' => 'Guardar / Editar {title} del Grid',
    'Save / edit grid {category}' => 'Guardar / Editar {category} del Grid ',
    'Save grid settings' => 'Guardar la configuración del Grid',
    'Saved Filters' => 'Guardar filtros',
    'Saved Sorts' => 'Guardar orden',
    'Saving and applying configuration' => 'Guardar y aplicar la configuración',
    'Select a filter...' => 'Seleccionar filtro ...',
    'Select a sort...' => 'Seleccionar orden ...',
    'Select a theme...' => 'Seleccionar Tema...',
    'Select theme to style grid' => 'Selecciona un tema para  el Grid',
    'Select...' => 'Selecciona',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Introduce un nombre para guardar el estado actual de los filtros del Grid. También puedes seleccionar de la lista una configuración de filtros guardada,  para editarla o eliminarla.',
    'Set default grid filter criteria' => 'Criterio de filtro predeterminado',
    'Set default grid sort criteria' => 'Criterio de orden predeterminado',
    'Sort Configuration' => 'Configurar orden',
    'Sort Name' => 'Nombre del orden',
    'Trash' => 'Papelera',
    'Trashing all personalizations' => 'Elimimar todas las opciones personalizadas',
    'Visible Columns' => 'Columnas visibles',
    'ascending' => 'Ascendente',
    'descending' => 'Descendente',
    'rows per page' => 'Filas por página',
    'Personalize' => 'Personalizar',
];