<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'sort' => '',
    'Personalize' => '@@个性化@@',
    'Abort any changes and reset settings' => '放弃更改并重置设置',
    'Apply' => '应用',
    'Are you sure you want to delete the setting?' => '您确定要删除设置吗？',
    'Configure Order and Display of Grid Columns' => '配置列顺序和可视列',
    'Default Filter' => '默认过滤器',
    'Default Sort' => '默认排序规则',
    'Delete' => '删除',
    'Filter Configuration' => '配置过滤器',
    'Filter Name' => '过滤器名字',
    'Grid Theme' => '表格主题',
    'Hidden / Fixed Columns' => '隐藏 / 固定 列',
    'Integer between {min} to {max}' => '{min} 和 {max} 之间的整数',
    'Page Size' => '页面大小',
    'Personalize Grid Configuration' => '个性化表格配置',
    'Personalize grid settings' => '个性化表格设置',
    'Remove saved grid settings' => '删除已保存的表格设置',
    'Reset' => '重置',
    'Save' => '保存',
    'Save / Edit Grid {title}' => '保存 / 编辑 {title}表',
    'Save / edit grid {category}' => '保存 / 编辑 {category}表',
    'Save grid settings' => '保存表格设置',
    'Saved Filters' => '保存过滤器',
    'Saved Sorts' => '保存排序规则',
    'Saving and applying configuration' => '保存并应用配置',
    'Select a filter...' => '选择过滤器...',
    'Select a sort...' => '选择排序规则...',
    'Select a theme...' => '选择主题...',
    'Select theme to style grid' => '选择表格主题',
    'Select...' => '选择...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => '设置一个名称以保存当前{category}表的排序规则。您也可以从下面已保存的排序规则进行编辑或删除。',
    'Set default grid filter criteria' => '设置表格默认过滤条件',
    'Set default grid sort criteria' => '设置表格默认排序规则',
    'Sort Configuration' => '配置排序规则',
    'Sort Name' => '排序规则名',
    'Trash' => '删除',
    'Trashing all personalizations' => '删除所有自定义设置',
    'Visible Columns' => '可见列',
    'ascending' => '升序',
    'descending' => '降序',
    'filter' => '过滤器',
    'grid' => '表格',
    'rows per page' => '条 / 每页',
];
