<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'filter' => '',
    'grid' => '',
    'sort' => '',
    'Abort any changes and reset settings' => '中止任何更改并且重置设置',
    'Apply' => '应用',
    'Are you sure you want to delete the setting?' => '你确定要删除设置吗？',
    'Configure Order and Display of Grid Columns' => '配置列的顺序和显示',
    'Default Filter' => '默认筛选',
    'Default Sort' => '默认排序',
    'Delete' => '删除',
    'Filter Configuration' => '筛选配置',
    'Filter Name' => '筛选名称',
    'Grid Theme' => '表格主题',
    'Hidden / Fixed Columns' => '隐藏/固定 列',
    'Integer between {min} to {max}' => '整数在{min}到{max}之间',
    'Page Size' => '页大小',
    'Personalize Grid Configuration' => '自定义表格配置',
    'Personalize grid settings' => '自定义表格设置',
    'Remove saved grid settings' => '删除表格设置',
    'Reset' => '重置',
    'Save' => '保存',
    'Save / Edit Grid {title}' => '保存/编辑 表格{title}',
    'Save / edit grid {category}' => '保存/编辑 表格{category}',
    'Save grid settings' => '保存表格设置',
    'Saved Filters' => '保存筛选',
    'Saved Sorts' => '保存排序',
    'Saving and applying configuration' => '保存并应用配置',
    'Select a filter...' => '选择筛选',
    'Select a sort...' => '选择排序',
    'Select a theme...' => '选择主题',
    'Select theme to style grid' => '选择表格主题样式',
    'Select...' => '选择',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => '设置一个名称来保存当前表格的状态{category}。可以从下面的列表中选择一个保存的{category}，编辑或删除。',
    'Set default grid filter criteria' => '设置默认的表格筛选规则',
    'Set default grid sort criteria' => '设置默认的表格排序规则',
    'Sort Configuration' => '排序设置',
    'Sort Name' => '排序名称',
    'Trash' => '删除',
    'Trashing all personalizations' => '删除所有自定义设置',
    'Visible Columns' => '显示列',
    'ascending' => '升序',
    'descending' => '降序',
    'rows per page' => '每页行数',
];
