<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => 'REMARQUE: Lors de l\'édition d\'un enregistrement existant, le nom {category} et ses paramètres seront modifiés...',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => 'REMARQUE: Lors de l\'édition d\'un enregistrement existant, seul le nom {category} sera modifié (et non les paramètres)...',
    'Abort any changes and reset settings' => 'Annuler les modifications et réinitialiser les réglages',
    'Apply' => 'Appliquer',
    'Are you sure you want to delete the setting?' => 'Etes-vous sûr de vouloir supprimer le réglage?',
    'Configure Order and Display of Grid Columns' => 'Configuration de l\'ordre et affichage des colonnes du tableau des matières',
    'Default Filter' => 'Filtre par défaut',
    'Default Sort' => 'Tri par défaut',
    'Delete' => 'Supprimer',
    'Filter Configuration' => 'Configuration du filtre',
    'Filter Name' => 'Nom du filtre',
    'Grid Theme' => 'Thème tableau',
    'Hidden / Fixed Columns' => 'Colonnes cachées / fixes',
    'Integer between {min} to {max}' => 'Intégrer entre {min} à {max}.',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => 'Opération interdite! Signature de requête non valide détectée pour les paramètres dynagrid. {params}',
    'Page Size' => 'Taille de la page',
    'Personalize Grid Configuration' => 'Configuration du tableau personnalisée',
    'Personalize grid settings' => 'Personnaliser les réglages tableau',
    'Remove saved grid settings' => 'Supprimer les réglages enregistrés',
    'Reset' => 'Réinitialiser',
    'Save' => 'Sauvegarder',
    'Save / Edit Grid {title}' => 'Sauvegarder / Editer le tableau {title}.',
    'Save / edit grid {category}' => 'Sauvegarder / Editer le tableau {category}.',
    'Save grid settings' => 'Sauvegarder les paramètres du tableau',
    'Saved Filters' => 'Filtres enregistrés',
    'Saved Sorts' => 'Tris enregistrés',
    'Saving and applying configuration' => 'Enregistrer et appliquer la configuration',
    'Select a filter...' => 'Sélectionnez un filtre....',
    'Select a sort...' => 'Sélectionnez un tri...',
    'Select a theme...' => 'Sélectionnez un thème...',
    'Select theme to style grid' => 'Sélectionner un thème',
    'Select...' => 'Sélectionner...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Choisissez un nom pour sauvegarder l\'état de votre tableau actuel {category}. Vous pouvez également sélectionner une {category} sauvegardée dans la liste ci-dessous pour l\'éditer ou la supprimer.',
    'Set default grid filter criteria' => 'Selectionner le filtre par défaut',
    'Set default grid sort criteria' => 'Configuration des critères de tri du tableau par défaut',
    'Sort Configuration' => 'Configuration du tri',
    'Sort Name' => 'Nom du tri',
    'Trash' => 'Corbeille',
    'Trashing all personalizations' => 'Détruire toutes les personnalisations',
    'Visible Columns' => 'Colonnes visibles',
    'ascending' => 'ascendant',
    'descending' => 'descendant',
    'filter' => 'filtre',
    'grid' => 'tableau',
    'rows per page' => 'lignes par page',
    'sort' => 'tri',
 ];
