<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'Abort any changes and reset settings' => 'Wijzigingen vergeten en instellingen resetten',
    'Apply' => 'Toepassen',
    'Are you sure you want to delete the setting?' => 'Weet u zeker dat u uw instellingen wilt verwijderen?',
    'Configure Order and Display of Grid Columns' => 'Configureer sortering en weergave van de kolommen',
    'Default Filter' => 'Standaard filter',
    'Default Sort' => 'Standaard sortering',
    'Delete' => 'Verwijderen',
    'Filter Configuration' => 'Filter configuratie',
    'Filter Name' => 'Filter naam',
    'Grid Theme' => 'Grid thema',
    'Hidden / Fixed Columns' => 'Verborgen / vaste kolommen',
    'Integer between {min} to {max}' => 'Getal tussen {min} en {max}',
    'Page Size' => 'Aantal op pagina',
    'Personalize Grid Configuration' => 'Wijzig grid configuratie',
    'Personalize grid settings' => 'Wijzig grid instellingen',
    'Remove saved grid settings' => 'Verwijder opgeslagen instellingen',
    'Reset' => 'Reset',
    'Save' => 'Opslaan',
    'Save / Edit Grid {title}' => 'Wijzig grid {title}',
    'Save / edit grid {category}' => 'Wijzig grid {category}',
    'Save grid settings' => 'Grid instellingen opslaan',
    'Saved Filters' => 'Opgeslagen filters',
    'Saved Sorts' => 'Opgeslagen sortering',
    'Saving and applying configuration' => 'Configuratie opslaan en toepassen',
    'Select a filter...' => 'Selecteer een filter...',
    'Select a sort...' => 'Selecteer een sortering...',
    'Select a theme...' => 'Selecteer een thema...',
    'Select theme to style grid' => 'Selecteer grid stijl thema',
    'Select...' => 'Selecteer...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Kies een naam voor huidige status van het grid {category}. U kunt ook een opgeslagen {category} van de onderstaande lijst kiezen om te bewerken of te verwijderen.',
    'Set default grid filter criteria' => 'Stel standaard filter instellingen in',
    'Set default grid sort criteria' => 'Stel standaard sortering instellingen in',
    'Sort Configuration' => 'Sortering configuratie',
    'Sort Name' => 'Sortering naam',
    'Trash' => 'Prullenbak',
    'Trashing all personalizations' => 'Personalisatie wordt verwijderd',
    'Visible Columns' => 'Zichtbare kolommen',
    'ascending' => 'Oplopend',
    'descending' => 'Aflopend',
    'filter' => 'filter',
    'grid' => 'grid',
    'rows per page' => 'Rijen per pagina',
    'sort' => 'sorteer',
];
