<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'filter' => '',
    'grid' => '',
    'sort' => '',
    'Abort any changes and reset settings' => 'Zrušit změny a obnovit nastavení?',
    'Apply' => 'Použít',
    'Are you sure you want to delete the setting?' => 'Oprvadu chcete smazat nastavení?',
    'Configure Order and Display of Grid Columns' => 'Konfigurace pořadí a zobrazení sloupců',
    'Default Filter' => 'Výchozí filtr',
    'Default Sort' => 'Výchozí třídění',
    'Delete' => 'Smazat',
    'Filter Configuration' => 'Konfigurace filtru',
    'Filter Name' => 'Název filtru',
    'Grid Theme' => 'Šablona zobrazení tabulky',
    'Hidden / Fixed Columns' => 'Skryté / ukotvené sloupce',
    'Integer between {min} to {max}' => 'Celé číslo od {min} do {max}',
    'Page Size' => 'Velikost stránky',
    'Personalize Grid Configuration' => 'Uživatelské nastavení tabulky',
    'Personalize grid settings' => 'Uživatelské nastavení tabulky',
    'Remove saved grid settings' => 'Odstranit uložené nastavení tabulky',
    'Reset' => 'Obnovit',
    'Save' => 'Uložit',
    'Save / Edit Grid {title}' => 'Uložit / editovat tabulku {title}',
    'Save / edit grid {category}' => 'Uložit / editovat {category} tabulky',
    'Save grid settings' => 'Uložit nastavení tabulky',
    'Saved Filters' => 'Uložené filtry',
    'Saved Sorts' => 'Uložená třídění',
    'Saving and applying configuration' => 'Ukládání nastavení',
    'Select a filter...' => 'Vyberte filtr...',
    'Select a sort...' => 'Vyberte třídění...',
    'Select a theme...' => 'Vyberte šablonu zobrazení',
    'Select theme to style grid' => 'Vyberte šablonu pro zobrazení tabulky',
    'Select...' => 'Vyberte...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Zadejte jméno pro uložení nastavení {category}. Můžete také vybrat již uložené nastavení ze spodního seznamu pro přepsání/smazání exisstujícího uložného nastavení.',
    'Set default grid filter criteria' => 'Nastavení výchozího filtru tabulky',
    'Set default grid sort criteria' => 'Nastavení výchozího třídění tabulky',
    'Sort Configuration' => 'Konfigurace třídění',
    'Sort Name' => 'Název třídění',
    'Trash' => 'Koš',
    'Trashing all personalizations' => 'Smazat všechna nastavení?',
    'Visible Columns' => 'Zobrazené sloupce',
    'ascending' => 'vzestupně',
    'descending' => 'sestupně',
    'rows per page' => 'řádků na stránce',
];
