<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apply' => 'Übernehmen',
    'Reset' => 'Zurücksetzen',
    'Personalize' => 'Personalisieren',
    'Personalize Grid Configuration' => 'Einstellungen personalisieren',
    'Saving and applying configuration' => 'Speichere und übernehme Einstellungen',
    'Grid Page Size' => 'Seitengröße',
    'Enter any integer between {min} to {max}.' => 'Gebene Sie eine Zahl zwischen {min} und {max} ein',
    'Grid Theme' => 'Aussehen',
    'Select a theme to style your grid.' => 'Wähle ein Thema um das Aussehen zu bearbeiten',
    'Visible Columns' => 'Sichtbare Spalten',
    'Hidden / Fixed Columns' => 'Versteckte / Fixierte Spalten',
    'Configure Order and Display of Grid Columns' => 'Bearbeite die Reihenfolge und Sichtbarkeit von Spalten',
    'rows per page' => 'Zeilen pro Seite',
];
