<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort any changes and reset settings' => 'Abbruch Änderungen und Einstellungen zurücksetzen',
    'Apply' => 'Übernehmen',
    'Are you sure you want to delete the setting?' => 'Sind Sie sicher, Sie wollen, um die Einstellung zu löschen?',
    'ascending' => 'aufsteigend',
    'Configure Order and Display of Grid Columns' => 'Bearbeite die Reihenfolge und Sichtbarkeit von Spalten',
    'Default Filter' => 'Standard Filter',
    'Default Sort' => 'Standard Sort',
    'Delete' => 'Löschen',
    'descending' => 'absteigend',
    'Filter Configuration' => 'Filter Konfiguration',
    'Filter Name' => 'Filter Namen',
    'Grid Theme' => 'Aussehen',
    'Hidden / Fixed Columns' => 'Versteckte / Fixierte Spalten',
    'Integer between {min} to {max}' => 'Zahl zwischen {min} und {max} ein',
    'Page Size' => 'Seitengröße',
    'Personalize' => 'Personifizieren',
    'Personalize Grid Configuration' => 'Einstellungen personalisieren',
    'Personalize grid settings' => 'Personalisieren raster einstellungen',
    'Remove saved grid settings' => 'Entfernen gespeichert raster einstellungen',
    'Reset' => 'Zurücksetzen',
    'rows per page' => 'Zeilen pro Seite',
    'Save' => 'Speichern',
    'Save / Edit Grid {title}' => 'Speichern / Bearbeiten Raster {title}',
    'Save / edit grid {category}' => 'Speichern / bearbeiten raster {category}',
    'Save grid settings' => 'Speichern raster {settings}',
    'Saved Filters' => 'Gespeicherte Filter',
    'Saved Sorts' => 'Gespeichert Sorts',
    'Saving and applying configuration' => 'Speichere und übernehme Einstellungen',
    'Select a filter...' => 'Wählen Sie einen Filter...',
    'Select a sort...' => 'Wählen Sie eine Art...',
    'Select a theme...' => 'Wählen Sie ein Thema...',
    'Select theme to style grid' => 'Thema auswählen, um Stil Gitter',
    'Select...' => 'Wählen...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => '',
    'Set default grid filter criteria' => 'Festlegen von standard raster filter kriterien',
    'Set default grid sort criteria' => 'Festlegen von standard raster sortier kriterien',
    'Sort Configuration' => 'Configuration Sortieren',
    'Sort Name' => 'Sortieren Namen',
    'Trash' => 'Müll',
    'Trashing all personalizations' => 'Wegwerfen alle Personalisierungen',
    'Visible Columns' => 'Sichtbare Spalten',
];