<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'filter' => '',
    'grid' => '',
    'sort' => '',
    0 => '@@Legen Sie einen Namen fest, unter dem die aktuelle Konfiguration gespeichert werden soll. Alternativ wählen Sie einen gespeicherten Filter aus um diesen zu bearbeiten/löschen@@',
    'Abort any changes and reset settings' => 'Änderungen verwerfen und Einstellungen zurücksetzen',
    'Apply' => 'Übernehmen',
    'Are you sure you want to delete the setting?' => 'Sind Sie sicher, dass Sie die Einstellungen löschen möchten?',
    'Configure Order and Display of Grid Columns' => 'Bearbeite die Reihenfolge und Sichtbarkeit der Spalten',
    'Default Filter' => 'Standardfilter',
    'Default Sort' => 'Standardsortigung',
    'Delete' => 'Löschen',
    'Filter Configuration' => 'Filterkonfiguration',
    'Filter Name' => 'Filternamen',
    'Grid Theme' => 'Design',
    'Hidden / Fixed Columns' => 'Versteckte / Fixierte Spalten',
    'Integer between {min} to {max}' => 'Zahl zwischen {min} und {max}',
    'Page Size' => 'Seitengröße',
    'Personalize Grid Configuration' => 'Einstellungen anpassen',
    'Personalize grid settings' => 'Einstellungen anpassen',
    'Remove saved grid settings' => 'Gespeicherte Einstellungen löschen',
    'Reset' => 'Zurücksetzen',
    'Save' => 'Speichern',
    'Save / Edit Grid {title}' => 'Ansicht {title} speichern / bearbeiten',
    'Save / edit grid {category}' => '{category} speichern / bearbeiten',
    'Save grid settings' => 'Einstellungen speichern',
    'Saved Filters' => 'Gespeicherte Filter',
    'Saved Sorts' => 'Gespeichert Sortierungen',
    'Saving and applying configuration' => 'Einstellungen werden übernommen und gespeichert',
    'Select a filter...' => 'Wählen Sie einen Filter...',
    'Select a sort...' => 'Wählen Sie eine Sortierung...',
    'Select a theme...' => 'Wählen Sie ein Design...',
    'Select theme to style grid' => 'Design auswählen',
    'Select...' => 'Auswählen...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Wählen Sie einen Namen um die Aktuelle Auswahl für {category} zu speichern. Alternativ können Sie eine bestehende {category} aus der Liste auswählen und diese bearbeiten oder entfernen.',
    'Set default grid filter criteria' => 'Standardfilter festlegen',
    'Set default grid sort criteria' => 'Standardsortierung festlegen',
    'Sort Configuration' => 'Sortierung konfigurieren',
    'Sort Name' => 'Name der Sortierung',
    'Trash' => 'Löschen',
    'Trashing all personalizations' => 'Alle Einstellungen löschen',
    'Visible Columns' => 'Sichtbare Spalten',
    'ascending' => 'aufsteigend',
    'descending' => 'absteigend',
    'rows per page' => 'Zeilen pro Seite',
];
