<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified.' => 'ПРИМІТКА. Під час редагування існуючого запису будуть зміненні ім\'я {category} та його параметри.',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings).' => 'ПРИМІТКА. Під час редагування існуючого запису буде змінено лише ім\'я запису {category} (а не налаштування).',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => 'Операція заборонена! Невірний підпис запиту виявлено для налаштувань динамічної таблиці. {params}',
    'filter' => 'фільтрування',
    'grid' => 'таблиця',
    'sort' => 'сортування',
    'Abort any changes and reset settings' => 'Скасувати всі зміни і скинути налаштування',
    'Apply' => 'Застосувати',
    'Are you sure you want to delete the setting?' => 'Ви впевнені в тому, що хочете видалити налаштування?',
    'Configure Order and Display of Grid Columns' => 'Налаштувати порядок і відображення колонок',
    'Default Filter' => 'Фільтр за замовчуванням',
    'Default Sort' => 'Сортування за замовчуванням',
    'Delete' => 'Видалити',
    'Filter Configuration' => 'Конфігурація фільтра',
    'Filter Name' => 'Назва фільтру',
    'Grid Theme' => 'Тема оформлення таблиці',
    'Hidden / Fixed Columns' => 'Приховані / Фіксовані колонки',
    'Integer between {min} to {max}' => 'Число від {min} і до {max}',
    'Page Size' => 'Записів на сторінці',
    'Personalize Grid Configuration' => 'Налаштування таблиці',
    'Personalize grid settings' => 'Персоналізувати налаштування таблиці',
    'Remove saved grid settings' => 'Видалити збережені настройки таблиці',
    'Reset' => 'Скинути',
    'Save' => 'Зберегти',
    'Save / Edit Grid {title}' => 'Зберегти / змінити {title} таблиці',
    'Save / edit grid {category}' => 'Зберегти / змінити {category} таблиці',
    'Save grid settings' => 'Зберегти налаштування таблиці',
    'Saved Filters' => 'Збережені фільтри',
    'Saved Sorts' => 'Збережені сортування',
    'Saving and applying configuration' => 'Зберегти та застосувати',
    'Select a filter...' => 'Виберіть фільтр...',
    'Select a sort...' => 'Виберіть сортування...',
    'Select a theme...' => 'Виберіть тему...',
    'Select theme to style grid' => 'Виберіть тему для оформлення таблиці',
    'Select...' => 'Виберіть...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Вкажіть ім\'я для збереження поточного стану {category} таблиці. Додатково, ви можете вибрати збережений стан {category} таблиці з нижченаведеного списку для його зміни або видалення.',
    'Set default grid filter criteria' => 'Встановити критерій фільтра за замовчуванням',
    'Set default grid sort criteria' => 'Встановити критерій сортування за замовчуванням',
    'Sort Configuration' => 'Конфігурація сортування',
    'Sort Name' => 'Назва сортування',
    'Trash' => 'Видалити',
    'Trashing all personalizations' => 'Видалити всі налаштування',
    'Visible Columns' => 'Відображені колонки',
    'ascending' => 'за зростанням',
    'descending' => 'за зменшенням',
    'rows per page' => 'рядків на сторінці',
];
