<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Hidden / Fixed Columns' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'grid' => '',
    'Personalize' => '@@Personalizza@@',
    'Abort any changes and reset settings' => 'Annula i cambiamenti e reimposta le opzioni',
    'Apply' => 'Applica',
    'Are you sure you want to delete the setting?' => 'Site sicuri di voler eliminare le impostazioni?',
    'Configure Order and Display of Grid Columns' => 'Configura Ordine e Visibilità delle colonne',
    'Default Filter' => 'Filtro di predefinito',
    'Default Sort' => 'Ordinamento Predefinito',
    'Delete' => 'Elimina',
    'Filter Configuration' => 'Configura Filtro',
    'Filter Name' => 'Nome Filtro',
    'Grid Theme' => 'Tema Griglia',
    'Integer between {min} to {max}' => 'Intero tra {min} e {max}',
    'Page Size' => 'Dimensione Pagina',
    'Personalize Grid Configuration' => 'Personalizza Configurazione Griglia',
    'Personalize grid settings' => 'Personalizza le impostazioni della griglia',
    'Remove saved grid settings' => 'Elimina le impostaioni salvate della griglia',
    'Reset' => 'Reimposta',
    'Save' => 'Salva',
    'Save / Edit Grid {title}' => 'Salva / Modifica {title} Griglia',
    'Save / edit grid {category}' => 'Salva / modifica {category} griglia',
    'Save grid settings' => 'Salva impostazioni griglia',
    'Saved Filters' => 'Filtri Salvati',
    'Saved Sorts' => 'Ordinamenti Salvati',
    'Saving and applying configuration' => 'Salva e applica configurazione',
    'Select a filter...' => 'Seleziona filtro...',
    'Select a sort...' => 'Seleziona ordinamento...',
    'Select a theme...' => 'Seleziona tema...',
    'Select theme to style grid' => 'Seleziona un tema per la griglia',
    'Select...' => 'Seleziona...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Imposta un nome per salvare lo stato corrente di {category} della griglia. In alternativa potete selezionare un {category} dalla lista seguente per modificare o eliminare',
    'Set default grid filter criteria' => 'Imposta il filtro di default della griglia',
    'Set default grid sort criteria' => 'Imposta l\'ordinamento di default della griglia',
    'Sort Configuration' => 'Configura Ordinamento',
    'Sort Name' => 'Nome Ordinamento',
    'Trash' => 'Cestina',
    'Trashing all personalizations' => 'Cestina tutte le personalizzazioni',
    'Visible Columns' => 'Colonne Visibili',
    'ascending' => 'ascendente',
    'descending' => 'discendente',
    'filter' => 'filtro',
    'rows per page' => 'righe per pagina',
    'sort' => 'ordinamento',
];
