<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'filter' => '',
    'grid' => '',
    'sort' => '',
    'Abort any changes and reset settings' => 'Visszaállítás alap beállításra.',
    'Apply' => 'Alkalmaz',
    'Are you sure you want to delete the setting?' => 'Beállítások törlése?',
    'Configure Order and Display of Grid Columns' => 'Oszlopok sorrendjének és láthatóságának beállítása',
    'Default Filter' => 'Alapértelmezett szűrő',
    'Default Sort' => 'Alapértelmzett rendezés',
    'Delete' => 'Törlés',
    'Filter Configuration' => 'Szűrő beállítás',
    'Filter Name' => 'Szűrő név',
    'Grid Theme' => 'Táblázat nézet',
    'Hidden / Fixed Columns' => 'Rejtett / Rögzített oszlopok',
    'Integer between {min} to {max}' => 'Egész szám ({min}-tól {max}-ig)',
    'Page Size' => 'Száma oldalanként',
    'Personalize Grid Configuration' => 'Táblázat beállításainak testreszabása',
    'Personalize grid settings' => 'Tábla személyreszabás',
    'Remove saved grid settings' => 'Tábla beállítások törlése',
    'Reset' => 'Alaphelyzet',
    'Save' => 'Mentés',
    'Save / Edit Grid {title}' => 'Mentés / Szerkesztés',
    'Save / edit grid {category}' => 'Mentés / Szerkesztés',
    'Save grid settings' => 'Tábla beállítások mentése',
    'Saved Filters' => 'Szűrők mentése',
    'Saved Sorts' => 'Rendezések mentése',
    'Saving and applying configuration' => 'Beállítások mentése és alkalmazása',
    'Select a filter...' => 'Szűrők',
    'Select a sort...' => 'Rendezés',
    'Select a theme...' => 'Nézet',
    'Select theme to style grid' => 'Tábla nézet választása',
    'Select...' => 'Választ:',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Név megadása a tábla beállításainak elmentéséhez.',
    'Set default grid filter criteria' => 'Alapértelmezett tábla szűrő',
    'Set default grid sort criteria' => 'Alapértelmezett tábla rendezés',
    'Sort Configuration' => 'Rendezés beállítása',
    'Sort Name' => 'Rendezés név',
    'Trash' => 'Szemetes',
    'Trashing all personalizations' => 'Minden személyreszabás törlése',
    'Visible Columns' => 'Megjelenítendő oszlopok',
    'ascending' => 'Emelkedő',
    'descending' => 'Csökkenő',
    'rows per page' => 'Sor/Oldal',
];
