<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apply' => 'Alkalmaz',
    'Reset' => 'Alaphelyzet',
    'Personalize' => 'Testreszabás',
    'Personalize Grid Configuration' => 'Táblázat beállításainak testreszabása',
    'Saving and applying configuration' => 'Beállítások mentése és alkalmazása',
    'Grid Page Size' => 'Sorok száma oldalanként',
    'Enter any integer between {min} to {max}.' => 'Adjon meg egy {min} és {max} közé eső egész számot',
    'Grid Theme' => 'Táblázat kinézete',
    'Select a theme to style your grid.' => 'Válassza ki a táblázat kinézetét',
    'Visible Columns' => 'Megjelenítendő oszlopok',
    'Hidden / Fixed Columns' => 'Rejtett / Rögzített oszlopok',
    'Configure Order and Display of Grid Columns' => 'Oszlopok sorrendjének és láthatóságának beállítása',
    'rows per page' => 'sorok száma oldalnként',
];
