<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified..' => '',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings)..' => '',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'filter' => '',
    'grid' => '',
    'sort' => '',
    'Abort any changes and reset settings' => 'Anuluj zmiany i przywróć ustawienia',
    'Apply' => 'Zastosuj',
    'Are you sure you want to delete the setting?' => 'Czy na pewno usunąć ustawienia?',
    'Configure Order and Display of Grid Columns' => 'Skonfiguruj kolejność i wyświetlanie kolumn siatki',
    'Default Filter' => 'Domyślny filtr',
    'Default Sort' => 'Domyślne sortowanie',
    'Delete' => 'Usuń',
    'Filter Configuration' => 'Ustawienia filtra',
    'Filter Name' => 'Nazwa filtra',
    'Grid Theme' => 'Motyw siatki',
    'Hidden / Fixed Columns' => 'Ukryte / stałe kolumny',
    'Integer between {min} to {max}' => 'Liczba całkowita pomiędzy {min} i {max}',
    'Page Size' => 'Wyników na stronę',
    'Personalize Grid Configuration' => 'Spersonalizuj konfigurację siatki',
    'Personalize grid settings' => 'Spersonalizuj ustawienia siatki',
    'Remove saved grid settings' => 'Usuń zapisane ustawienia siatki',
    'Reset' => 'Resetuj',
    'Save' => 'Zapisz',
    'Save / Edit Grid {title}' => 'Zapisz / edytuj siatkę {title}',
    'Save / edit grid {category}' => 'Zapisz / edytuj siatkę {category}',
    'Save grid settings' => 'Zapisz ustawienia siatki',
    'Saved Filters' => 'Zapisane filtry',
    'Saved Sorts' => 'Zapisana kolejność sortowania',
    'Saving and applying configuration' => 'Zapisywanie i ładowanie konfiguracji',
    'Select a filter...' => 'Wybierz filtr...',
    'Select a sort...' => 'Wybierz kolejność sortowania...',
    'Select a theme...' => 'Wybierz motyw...',
    'Select theme to style grid' => 'Wybierz motyw stylu siatki',
    'Select...' => 'Wybierz...',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Wybierz nazwę, aby zapisać stan aktualnej siatki {category}. Możesz również wybrać zapisaną {category} z listy poniżej w celu edycji lub jej usunięcia.',
    'Set default grid filter criteria' => 'Ustaw domyślne kryteria filtra siatki',
    'Set default grid sort criteria' => 'Ustaw domyślne kryteria kolejności sortowania siatki',
    'Sort Configuration' => 'Sortuj konfigurację',
    'Sort Name' => 'Sortuj nazwę',
    'Trash' => 'Usuń',
    'Trashing all personalizations' => 'Usuwanie wszystkich personalizacji',
    'Visible Columns' => 'Widoczne kolumny',
    'ascending' => 'rosnąco',
    'descending' => 'malejąco',
    'rows per page' => 'wierszy na stronę',
];
