<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abort any changes and reset settings' => '',
    'Apply' => '',
    'Are you sure you want to delete the setting?' => '',
    'Configure Order and Display of Grid Columns' => '',
    'Default Filter' => '',
    'Default Sort' => '',
    'Delete' => '',
    'Filter Configuration' => '',
    'Filter Name' => '',
    'Grid Theme' => '',
    'Hidden / Fixed Columns' => '',
    'Integer between {min} to {max}' => '',
    'Page Size' => '',
    'Personalize Grid Configuration' => '',
    'Personalize grid settings' => '',
    'Remove saved grid settings' => '',
    'Reset' => '',
    'Save' => '',
    'Save / Edit Grid {title}' => '',
    'Save / edit grid {category}' => '',
    'Save grid settings' => '',
    'Saved Filters' => '',
    'Saved Sorts' => '',
    'Saving and applying configuration' => '',
    'Select a filter...' => '',
    'Select a sort...' => '',
    'Select a theme...' => '',
    'Select theme to style grid' => '',
    'Select...' => '',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => '',
    'Set default grid filter criteria' => '',
    'Set default grid sort criteria' => '',
    'Sort Configuration' => '',
    'Sort Name' => '',
    'Trash' => '',
    'Trashing all personalizations' => '',
    'Visible Columns' => '',
    'ascending' => '',
    'descending' => '',
    'rows per page' => '',
    'Personalize' => '@@@@',
];